### ISSUE TITLE
Error at quatUtils.py

### ISSUE THREAD

**Issue by ryohachiuma** [nileshkulkarni/volumetricPrimitivesPytorch#1]
Hi, Thanks for providing the implementation of pytorch!
I'm so grad!

When I run unit-test of quatUtils.py, I got the following error.

```
uatUtils.py:143: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  assert torch.abs(1 - dot_p).data[0] < 1E-4, 'Conjugate is incorrect'
Traceback (most recent call last):
  File "quatUtils.py", line 198, in <module>
    test_hamilton_product()
  File "quatUtils.py", line 159, in test_hamilton_product
    quat_product = hamilton_product(quat1, quat1_c)
  File "quatUtils.py", line 88, in hamilton_product
    q2_permute_0 = q2_permute_0 * np.sign(inds[i][0] + 0.01)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'
```

Do you have any suggestions?

Thanks!

**Comment by ryohachiuma** [comment]
I solved by changing to 
```
q2_permute_0 = q2_permute_0 * np.sign(inds[i][0].float() + 0.01)
```

However, I got the following error.
```
  File "modules/quatUtils.py", line 103, in hamilton_product
    q_ham = torch.cat(q1_q2_prods, dim=2)
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)
```

**Comment by nileshkulkarni** [comment]
Just to verify, you are using Python3.6 and PyTorch Version 0.1.12.
I am sorry this was not part of the ReadMe. I have checked the above code with PyTorch 0.1.12

**Comment by nileshkulkarni** [comment]
So what I believe is the issue is that since you are maybe using version 0.2 onwards. torch.sum(t, dim=2) results in a 2D tensor, and hence torch.cat(q1_q2_prods,dim=2) is not a correct operation.

A small fix would be to change the following [line](https://github.com/nileshkulkarni/volumetricPrimitivesPytorch/blob/367d2bc3f7d2ec122c4e2066c2ee2a922cf4e0c8/modules/quatUtils.py#L100)
`q1q2_v1 = torch.sum(q1 * q2_permute, dim=2)`
to
`q1q2_v1 = torch.sum(q1 * q2_permute, dim=2).unsqueeze(2)`

Hope this helps.

**Comment by kemangjaka** [comment]
Hi, Thanks for the comment.
I downgrade Pytorch version to 0.1.12, and it successfully worked!


I saw the visualized result, and realized that the size of predicted primitive shapes and input CAD models are different. 
In the picture I attached, the left is predicted primitive shapes, and the right image is input CAD model. 
Do you have any ideas what was happened?
![Uploading image.png…]()

I also tried to visualize the result of official implementation. There was no difference of sizes between input CAD models and primitive shapes.

**Comment by ryohachiuma** [comment]
Hi, Thanks for the comment.
I downgrade Pytorch version to 0.1.12, and it successfully worked!

I saw the visualized result, and realized that the size of predicted primitive shapes and input CAD models are different.
In the picture I attached, the left is predicted primitive shapes, and the right image is input CAD model.
Do you have any ideas what was happened? (I'm sorry there was Japanese in the picture, but I visualized the model by 3D builder on Windows)
![default](https://user-images.githubusercontent.com/18188980/41658468-6399607c-74d1-11e8-93fe-44e3b5df0196.PNG)

I also tried to visualize the result of official implementation. There was no difference of sizes between input CAD models and primitive shapes.

**Comment by nileshkulkarni** [comment]
Interesting I did not have such a difference in sizes.
To my knowledge when the models are converted from obj to TSDF shapes it is made sure that they fit inside a unit cube centered around origin. 
Did you visualize the results just for the first stage of training. If they look fine or not? 
Let me know if you find anything else.

**Comment by ryohachiuma** [comment]
Thanks, maybe something I have changed your code if you didn't get anything wrong. 
I will debug my code again, and let you know if I found something.
