### ISSUE TITLE
params.shapeLrDecay and params.shapeLrDecay

### ISSUE THREAD

**Issue by esizikova** [nileshkulkarni/volumetricPrimitivesPytorch#3]
What do params.shapeLrDecay and params.shapeLrDecay represent?

**Comment by nileshkulkarni** [comment]
It basically controls the learning rate for shape module for the size of the shape. 
It is an optimization need, that we learn the shape (height, width, depth) of the primitives at a lower rate than other parameters (trans, quaternion)
