### ISSUE TITLE
TSDF loss always 0

### ISSUE THREAD

**Issue by yfyang16** [nileshkulkarni/volumetricPrimitivesPytorch#4]
Hi, when I was training the model, the TSDF loss was always zero.  How can I fix this problem?
The printed info is as follows.
1.0000000	 0.0001875	 0.0000000	 0.0001875	 0.0000000
 2.0000000	 0.0019047	 0.0000000	 0.0019047	 0.0000000
 3.0000000	 0.0004836	 0.0000000	 0.0004836	 0.0000000
 4.0000000	 0.0004276	 0.0000000	 0.0004276	 0.0000000
 5.0000000	 0.0004112	 0.0000000	 0.0004112	 0.0000000
 6.0000000	 0.0003436	 0.0000000	 0.0003436	 0.0000000
 7.0000000	 0.0002234	 0.0000000	 0.0002234	 0.0000000
 8.0000000	 0.0001804	 0.0000000	 0.0001804	 0.0000000
 9.0000000	 0.0000616	 0.0000000	 0.0000616	 0.0000000
10.0000000	 0.0000771	 0.0000000	 0.0000771	 0.0000000
...

**Comment by mansiag** [comment]
I am getting same problem. @nileshkulkarni Can you suggest how to resolve this issue?

**Comment by nileshkulkarni** [comment]
Hi,

I'm not sure why the TSDF loss is zero. I suspect multiple issues that might lead to the problem. 
[Here](https://www.dropbox.com/s/z1j1d3p9deev9fh/shapenet.tar.gz?dl=0) is the chamfer-data I'm using. It is small subset.  The other possible reason is the pytorch version is not matching. 
It  would be great if you could make sure the version matches and try again with the small subset of data available at the link

This is how my training looks like in the initial stages on the small set.
![image](https://user-images.githubusercontent.com/2604793/62803023-5935f280-bab7-11e9-8557-6e0c16f8b46f.png)

Also some more details on the problem would be helpful.

**Comment by mansiag** [comment]
Yes, the problem is solved now. Thanks.
