### ISSUE TITLE
'SimpleCadData' object has no attribute 'forwardTestSequential'

### ISSUE THREAD

**Issue by JingyiLi-612** [nileshkulkarni/volumetricPrimitivesPytorch#5]
when I run volumetricPrimitivesPytorch/test/cadAutoEncCuboids/primSelTsdfChamfer.py
I got the following error:
`Iter    Err     TSDF    Chamf
Traceback (most recent call last):
  File "cadAutoEncCuboids/primSelTsdfChamfer.py", line 148, in <module>
    sample, tsdfGt, sampledPoints = dataloader.forwardTestSequential()
AttributeError: 'SimpleCadData' object has no attribute 'forwardTestSequential'`

I checked the source code and did not find the attribute 'forwardTestSequential'.
How can I fix this problem?

**Comment by nileshkulkarni** [comment]
Try changing it to forwardTest(). There is no function called forwardTestSequential. It must have been a typo. Thanks for pointing out.

**Comment by JingyiLi-612** [comment]
> Try changing it to forwardTest(). There is no function called forwardTestSequential. It must have been a typo. Thanks for pointing out.

Thank you! It works!
