### ISSUE TITLE
What does "Tsdf" in the code stands for?

### ISSUE THREAD

**Issue by yichao-liang** [nileshkulkarni/volumetricPrimitivesPytorch#9]
Hi Nilesh, 

I'm an undergrad student working on shape primitives decomposition and found the "Learning Shape Abstractions by Assembling Volumetric Primitives" paper, your project extremely interesting.

But I'm quite confused by the acronym "Tsdf". I'm guessing "df" stands for "distance field" but couldn't come up with a good hypothesis for "Ts" after much thinking (is it transformed?).

Could you please hint me at what they are referring to? It'd be really helpful.

Best,
Yichao

**Comment by nileshkulkarni** [comment]
Hi,

TSDF stands for truncated signed distance function

Best,
Nilesh
